version: '2.2'
services:
  etcd:
    image: quay.io/coreos/etcd:v3.3.12
    container_name: etcd-v3
    ports:
      - 2379:2379
      - 2380:2380
    environment:
      ETCDCTL_API: 3
    volumes:
      - /Users/houchaoyue/docker-project/etcd/etcd-data:/etcd-data
    command:
      - "/usr/local/bin/etcd"
      - "--name"
      - "s1"
      - "--data-dir"
      - "/etcd-data"
      - "--advertise-client-urls"
      - "http://0.0.0.0:2379"
      - --listen-client-urls
      - "http://0.0.0.0:2379"
      - "--initial-advertise-peer-urls"
      - "http://0.0.0.0:2380"
      - "--listen-peer-urls"
      - "http://0.0.0.0:2380"
      - "--initial-cluster-token"
      - "tkn"
      - "--initial-cluster"
      - "s1=http://0.0.0.0:2380"
      - "--initial-cluster-state"
      - "new"
#etcd_v3版本使用
  etcd-manage:
    #build: .
    image: etcd-manager:v1
    volumes:
      - ./bin/config/cfg.toml:/app/config/cfg.toml
      - ./bin/logs:/app/logs
    ports:
      - "10280:10280"
    depends_on:
      - etcd
#etcd_v2版本使用
#  etcd-browser:
#    image: buddho/etcd-browser
#    container_name: etcd-browser
#    ports:
#     - 8000:8000
#    environment:
#      ETCD_HOST: etcd
#      ETCD_PORT: 2379
