version: '2'
networks:
  pub:
    external: true
services:
   c1:
      restart: always
      networks:
         pub:
            ipv4_address: 172.20.10.21
      image: tomcat
      container_name: tomcat
      ports:
        - 8080:8080
      volumes:
        - ./webapps:/usr/local/tomcat/webapps
      environment:
        TZ: Asia/Shanghai
