version: "3"
networks:
  pub:
    external: true
services:
    registry:
        networks:
           pub:
              ipv4_address: 172.20.10.141
        image: registry:2
        container_name: "docker-registry"
        restart: always
        ports:
            - 8150:5000
        volumes:
            - ./data:/var/lib/registry
            - ./auth:/auth
            - ./conf/config.yml:/etc/docker/registry/config.yml
