version: "3"

services:
    registry:
        image: registry:2
        container_name: "docker-registry"
        restart: always
        ports:
            - 8150:5000
        volumes:
            - ./data:/var/lib/registry
            - ./auth:/auth
            - ./conf/config.yml:/etc/docker/registry/config.yml
