version: '3.7'

# 给zk集群配置一个网络，网络名为zk-net
networks:
  pub:
    external: true

# 配置zk集群的
# container services下的每一个子配置都对应一个zk节点的docker container
services:
  zk1:
    # docker container所使用的docker image
    image: zookeeper
    hostname: zk1
    container_name: zk1
    # 配置docker container和宿主机的端口映射
    ports:
      - 2181:2181
      - 8081:8080
    # 配置docker container的环境变量
    environment:
      # 当前zk实例的id
      ZOO_MY_ID: 1
      # 整个zk集群的机器、端口列表
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888;2181 server.2=zk2:2888:3888;2181 server.3=zk3:2888:3888;2181
    # 将docker container上的路径挂载到宿主机上 实现宿主机和docker container的数据共享
    volumes:
      - ../../docker-volume/zookeeper/zk1/data:/data
      - ../../docker-volume/zookeeper/zk1/datalog:/datalog
    # 当前docker container加入名为zk-net的隔离网络
    networks:
       pub:
          ipv4_address: 172.20.10.181

  zk2:
    image: zookeeper
    hostname: zk2
    container_name: zk2
    ports:
      - 2182:2181
      - 8082:8080
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zk1:2888:3888;2181 server.2=0.0.0.0:2888:3888;2181 server.3=zk3:2888:3888;2181
    volumes:
      - ../../docker-volume/zookeeper/zk2/data:/data
      - ../../docker-volume/zookeeper/zk2/datalog:/datalog
    networks:
       pub:
          ipv4_address: 172.20.10.182

  zk3:
    image: zookeeper
    hostname: zk3
    container_name: zk3
    ports:
      - 2183:2181
      - 8083:8080
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zk1:2888:3888;2181 server.2=zk2:2888:3888;2181 server.3=0.0.0.0:2888:3888;2181
    volumes:
      - ../../docker-volume/zookeeper/zk3/data:/data
      - ../../docker-volume/zookeeper/zk3/datalog:/datalog
    networks:
       pub:
          ipv4_address: 172.20.10.183
