version: '2'
networks:
  pub:
    external: true
services:
  ansible-api:
    restart: always
    image: ansible-api:prod
    environment:
      MYSQL_HOST: 172.20.10.1
      MYSQL_USER: root
      MYSQL_DATABASE: md-admin
      MYSQL_PASSWD: insur132
      MYSQL_PORT: 3306
      MYSQL_CHARSET: utf8mb4
      REDIS_HOST: 172.20.10.11
      REDIS_PORT: 6379
      REDIS_PASSWD: 123456
    ports:
      - 8088:80
    volumes:
      - $PWD/logs:/logs
      - /etc/localtime:/etc/localtime
      - $PWD/script:/script
      - /Users/houchaoyue/Documents/zhongdianhuitong/ansible-worker-service:/ansible
      - $PWD/playbook:/playbook
    networks:
       pub:
          ipv4_address: 172.20.10.101

  mission:
    restart: always
    image: mission-worker:prod
    environment:
      MYSQL_HOST: 172.20.10.1
      MYSQL_USER: root
      MYSQL_DATABASE: md-admin
      MYSQL_PASSWD: insur132
      MYSQL_PORT: 3306
      MYSQL_CHARSET: utf8mb4
      REDIS_HOST: 172.20.10.11
      REDIS_PORT: 6379
      REDIS_PASSWD: 123456
      ANSIBLE_API: ansible-api:80
    volumes:
      - $PWD/logs:/logs
      - /etc/localtime:/etc/localtime
      - /Users/houchaoyue/Documents/zhongdianhuitong/ansible-worker-service:/converter
    ports:
      - 5555:5555
    networks:
       pub:
          ipv4_address: 172.20.10.102

