version: '3'
networks:
  pub:
    external: true
services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - $PWD/prometheus:/etc/prometheus
      - $PWD/prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    networks:
       pub:
          ipv4_address: 172.20.10.51
