version: '3.0'
networks:
    pub:
      external: true
services:
  canal-server:
    image: canal/canal-server:latest
    container_name: canal-server
    ports:
    #canal默认端口号
      - 11111:11111
    environment:
    #设置从库id，不能与主库id相冲突
      - canal.instance.mysql.slaveId=222
      - canal.instance.master.address=172.20.10.1:3306
      # mysql 复制账号
      - canal.instance.dbUsername=root
      - canal.instance.dbPassword=insur132
      - canal.mq.topic=CanalTopic
      #数据库名.表名
      - canal.instance.filter.regex=.login_log
    volumes:
      - ../../docker-volume/canal/conf/:/usr/local/dockercompose/canal/conf/
      - ../../docker-volume/canal/logs/:/usr/local/dockercompose/canal/logs/
    networks:
        pub:
            ipv4_address: 172.20.10.221