version: '3'
networks:
  pub:
    external: true
services:
  #服务名称
  sqlserver-db:
    #容器名称
    container_name: sqlserver-db
    #镜像名称
    image: microsoft/mssql-server-linux:latest
    #端口映射
    ports:
      - 1433:1433
    #挂载
    volumes:
      - ../../docker-volume/sql-server/data:/var/opt/mssql/data
    #环境变量
    environment:
      - ACCEPT_EULA=Y
      #SA用户密码长度必须至少为 8 个字符，并包含以下四组中的三组字符：大写字母、小写字母、10 位基数和符号
      - SA_PASSWORD=Sap123456789
    networks:
       pub:
          ipv4_address: 172.20.10.201
