version: '3.1'
services:
  jenkins:
    image: jenkins/jenkins:lts
    volumes:
      - $PWD/jenkins_home:/var/jenkins_home
      - $PWD/.ssh:/root/.ssh
      - /etc/localtime:/etc/localtime
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
    ports:
      - "8081:8080"
    expose:
      - "8081"
      - "50000"
    privileged: true
    user: root
    restart: always
    container_name: jenkins
    environment:
      JAVA_OPTS: "-Djava.util.logging.config.file=/var/jenkins_home/log.propertiesi -Duser.timezone=Asia/Shanghai"
