version: 0.1
log:
  fields:
    service: registry
storage:
  cache:
    blobdescriptor: inmemory
  filesystem:
    rootdirectory: /var/lib/registry
  delete:
    enabled: true
http:
  addr: :5000
  headers:
    X-Content-Type-Options: [nosniff]
auth:
  htpasswd:
    realm: zhixueyun
    path: /auth/httpasswd_storage/htpasswd
health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3
