version: '2'
networks:
  pub:
    external: true
services:
   c1:
      image: houchaoyue/host:latest
      restart: always
      tty: true
      volumes:
        - '../../docker-volume/ssh_host/:/data'
      networks:
         pub:
            ipv4_address: 172.20.0.1
   c2:
      image: houchaoyue/host:latest
      restart: always
      tty: true
      volumes:
        - '../../docker-volume/ssh_host/:/data'
      networks:
         pub:
            ipv4_address: 172.20.0.2
