version: '2'
   
networks:
  pub:
    external: true

services:
  influxdb:
    networks:
       pub:
          ipv4_address: 172.20.10.111
    container_name: influxdb
    image: influxdb:1.8.6
    restart: always
    #    ports:
    #      - "8086:8086"
    volumes:
      - $PWD/influxdb:/var/lib/influxdb
       
  chronograf:
    container_name: chronograf
    image: chronograf
    restart: always
    ports:
      - "48888:8888"
    volumes:
      - $PWD/chronograf:/var/lib/chronograf
    networks:
       pub:
          ipv4_address: 172.20.10.112
 
  telegraf:
    container_name: telegraf
    image: telegraf
    restart: always
    volumes:
      - $PWD/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    networks:
       pub:
          ipv4_address: 172.20.10.113

  kapacitor:
    container_name: kapacitor
    image: kapacitor
    restart: always
    #    ports:
    #      - "8092:9092"
    volumes:
      - $PWD/kapacitor/kapacitor.conf:/etc/kapacitor/kapacitor.conf:ro
    networks:
       pub:
          ipv4_address: 172.20.10.114
 
