version: '2'
networks:
  pub:
    external: true
services:
  nsqlookupd:
    image: nsqio/nsq
    command: /nsqlookupd
    ports:
      - 4160:4160
      - 4161:4161
    environment:
      HOSTNAME: 127.0.0.1
    networks:
       pub:
          ipv4_address: 172.20.10.171
  nsqd:
    image: nsqio/nsq
    command: /nsqd --lookupd-tcp-address=nsqlookupd:4160
    depends_on:
      - nsqlookupd
    ports:
      - 4150:4150
      - 4151:4151
    environment:
      HOSTNAME: 127.0.0.1
    networks:
       pub:
          ipv4_address: 172.20.10.172
  nsqadmin:
    image: nsqio/nsq
    command: /nsqadmin --lookupd-http-address=nsqlookupd:4161
    depends_on:
      - nsqlookupd  
    ports:
      - 4171:4171
    environment:
      HOSTNAME: 127.0.0.1
